from apengine._tests.infrastructure import *
startfile(__file__, "initial HFPs")

# Required HFPs. Here we check enforcement of rule 5.4 on the number of initial 
# HFPs required when transitioning from level to climbing/diving flight, between 
# climbing and diving flight, and between diving and climbing flight.

starttestsetup()
A1 = aircraft("A1", "F-80C", "1815", "N", 10, 4.0, "CL")
A2 = aircraft("A2", "F-80C", "2015", "N", 10, 4.0, "CL")
A3 = aircraft("A3", "F-80C", "2215", "N", 10, 4.0, "CL")
A4 = aircraft("A4", "F-80C", "2415", "N", 10, 4.0, "CL")
endtestsetup()

startturn()
A1.move("ZC" ,  "M", "C,H,H,H")
asserterror("insufficient initial HFPs.")
startturn()
A1.move("ZC" ,  "M", "H,H,H,C")
A1._assert("1812       N    11",  4.0)
A2.move("ZC" ,  "M", "H,C,H,H")
A2._assert("2012       N    11",  4.0)
A3.move("ZC" ,  "M", "H,H,H,C")
A3._assert("2212       N    11",  4.0)
A4.move("ZC" ,  "M", "H,H,H,C")
A4._assert("2412       N    11",  4.0)
endturn()

startturn()
A1.move("SD" ,  "N", "D,H,H,H")
asserterror("insufficient initial HFPs.")
startturn()
A2.move("SD" ,  "N", "H,D,H,H")
asserterror("insufficient initial HFPs.")
startturn()
A1.move("SD" ,  "N", "H,H,H,D")
A1._assert("1809       N    10",  4.0)
A2.move("SD" ,  "N", "H,H,H,D")
A2._assert("2009       N    10",  4.0)
A3.move("SD" ,  "N", "H,H,D,H")
A3._assert("2209       N    10",  4.0)
A4.move("ZC" ,  "M", "C,H,H,H")
A4._assert("2409       N    12",  4.0)
endturn()

starttestsetup()
A1 = aircraft("A1", "F-80C", "1815", "N", 10, 4.0, "CL")
A2 = aircraft("A2", "F-80C", "2015", "N", 10, 4.0, "CL")
A3 = aircraft("A3", "F-80C", "2215", "N", 10, 4.0, "CL")
A4 = aircraft("A4", "F-80C", "2415", "N", 10, 4.0, "CL")
endtestsetup()

startturn()
A1.move("SD" ,  "N", "D,H,H,H")
asserterror("insufficient initial HFPs.")
startturn()
A1.move("SD" ,  "N", "H,H,H,D")
A1._assert("1812       N     9",  4.0)
A2.move("SD" ,  "N", "H,D,H,H")
A2._assert("2012       N     9",  4.0)
A3.move("SD" ,  "N", "H,H,H,D")
A3._assert("2212       N     9",  4.0)
A4.move("SD" ,  "N", "H,H,H,D")
A4._assert("2412       N     9",  4.0)
endturn()


startturn()
A1.move("ZC" ,  "M", "C,H,H,H")
asserterror("insufficient initial HFPs.")
startturn()
A2.move("ZC" ,  "M", "H,C,H,H")
asserterror("insufficient initial HFPs.")
startturn()
A1.move("ZC" ,  "M", "H,H,H,C")
A1._assert("1809       N    10",  4.0)
A2.move("ZC" ,  "M", "H,H,H,C")
A2._assert("2009       N    10",  4.0)
A3.move("ZC" ,  "M", "H,H,C,H")
A3._assert("2209       N    10",  4.0)
A4.move("SD" ,  "N", "D,H,H,H")
A4._assert("2409       N     8",  4.0)
endturn()

endfile(__file__)