from apengine._tests.infrastructure import *
startfile(__file__, "damage effects")

starttestsetup()
A1 = aircraft("A1", "F-100C"  , "2025", "N", 5, 5.0, "CL")
endtestsetup()
startturn()
A1.move("LVL", "M", "ETR/H,H,H,H,H")
A1._assert("2020       N     5", 4.5)
endturn()

starttestsetup()
A1 = aircraft("A1", "F-100C"  , "2025", "N", 5, 5.0, "CL")
A1.takedamage("L")
endtestsetup()
startturn()
A1.move("LVL", "M", "ETR/H,H,H,H,H")
asserterror("attempt to declare a turn rate tighter than allowed by the damage, speed, or flight type.")
A1.move("LVL", "M", "BTR/H,H,H,H,H")
A1._assert("2020       N     5", 5.0)
endturn()

starttestsetup()
A1 = aircraft("A1", "F-100C"  , "2025", "N", 5, 5.0, "CL")
A1.takedamage("2L")
endtestsetup()
startturn()
A1.move("LVL", "M", "BTR/H,H,H,H,H")
asserterror("attempt to declare a turn rate tighter than allowed by the damage, speed, or flight type.")
A1.move("LVL", "M", "HTR/H,H,H,H,H")
A1._assert("2020       N     5", 5.0)
endturn()

starttestsetup()
A1 = aircraft("A1", "F-100C"  , "2025", "N", 5, 5.0, "CL")
A1.takedamage("H")
endtestsetup()
startturn()
A1.move("LVL", "M", "BTR/H,H,H,H,H")
asserterror("attempt to declare a turn rate tighter than allowed by the damage, speed, or flight type.")
A1.move("LVL", "M", "HTR/H,H,H,H,H")
A1._assert("2020       N     5", 5.0)
endturn()

starttestsetup()
A1 = aircraft("A1", "F-100C"  , "2025", "N", 5, 5.0, "CL")
A1.takedamage("C")
endtestsetup()
startturn()
A1.move("LVL", "M", "HTR/H,H,H,H,H")
asserterror("attempt to declare a turn rate tighter than allowed by the damage, speed, or flight type.")
A1.move("LVL", "M", "TTR/H,H,H,H,H")
A1._assert("2020       N     5", 5.0)
endturn()

endfile(__file__)