{
  "base": "land",
  "seahexes": [],
  "level0hexes": [],
  "level1hexes": [],
  "level2hexes": [],
  "level0ridges": [],
  "level1ridges": [],
  "level2ridges": [],
  "foresthexes": [],
  "town1hexes": [],
  "town2hexes": [],
  "town3hexes": [],
  "town4hexes": [],
  "town5hexes": [],
  "cityhexes": [],
  "lakehexes": [],
  "riverpaths": [],
  "wideriverpaths": [],
  "seapaths": [
  ],
  "wideseapaths": [
  ],
  "clearingpaths": [],
  ],
  "wideseapaths": [
  ],
  "clearingpaths": [],
  "trailpaths": [],
  "roadpaths": [],
  "dockpaths": [],
  "smallbridgepaths": [],
  "largebridgepaths": [],
  "runwaypaths": [],
  "taxiwaypaths": [],
  "dampaths": [],
  "tunnelpaths": [],
}
